### ISSUE TITLE
Owncloud status icon missing

### ISSUE THREAD

**Issue by dkerkow** [mank319/elementaryPlus#19]
Statusbar in Wingpanel shows a "missing icon" placeholder.

My System: Up-to-date Freya installation with Owncloud Client installed via PPA, elementaryPlus installed from git master.

**Comment by mank319** [comment]
Did you use the installer script?

**Comment by dkerkow** [comment]
Yes, I used the installer script.
Am 19.01.2015 20:25 schrieb "Manuel Kehl" <notifications@github.com>:

**Comment by cybre** [comment]
I'll look into it.

**Comment by cybre** [comment]
It turns out the latest version of OwnCloud Client actually uses the .svg's from the theme rather than the ones from the installer. This has been fixed now (Forgot to reference this issue in the commit message so I'll just close it now). Just download/clone the repository again and install/reinstall the theme.
