### ISSUE TITLE
Soundcloud icon for nuvola player

### ISSUE THREAD

**Issue by leafymind** [mank319/elementaryPlus#260]
I created an elementary like Soundcloud icon:

![soundcloud](https://cloud.githubusercontent.com/assets/2802675/8613489/11200aa4-26e0-11e5-9711-f43954c3895b.png)

I'm using it for https://github.com/AltarBeastiful/nuvola-app-soundcloud

**Comment by bil-elmoussaoui** [comment]
it's can be symlinked to soundcloud google application too

**Comment by quassy** [comment]
We actually do already have a [Nuvola icon](https://github.com/mank319/elementaryPlus/blob/master/elementaryPlus/apps/128/nuvolaplayer.svg) more similar to the original one. A Soundcloud icon would be great nontheless (if people want to use it for Nuvola they can easily use the Soundcloud icon instead of the Nuvola one).

**Comment by leafymind** [comment]
https://www.dropbox.com/s/3n8wgqe577zasbl/soundcloud-icons.tar.gz?dl=0

**Comment by quassy** [comment]
Thanks, your icon is now included in elementaryPlus! (Might take a while before it lands on a computer near you.)
