### ISSUE TITLE
Icon request: Synaptic

### ISSUE THREAD

**Issue by quassy** [mank319/elementaryPlus#32]
The current one is not only ugly but also blurry. (Probably needs a label "help wanted", but I can't assign that myself.)

**Comment by bil-elmoussaoui** [comment]
You can use this?
http://eos-snippets.blogspot.be/2014/12/fix-toolbar-synaptic-in-freya.html

**Comment by quassy** [comment]
In theory yes, the icon looks quite good, but it is only available in one size as a png file.

**Comment by mank319** [comment]
Multiple icon sizes are indeed important. On the other hand one could say "it is better than nothing". But in that case someone would have to keep an eye on the original theme in that regard, so that we do not overwrite any potential upstream fixes. I am not sure if we want that "maintenance responsibility".

**Comment by quassy** [comment]
This is closed for now with a symlink to the icon of AppCenter. Reopen for Loki / when AppCenter arrives.

**Comment by png2378** [comment]
Please reopen it. Loki with AppCenter is coming.
