### ISSUE TITLE
Icon request: Solaar

### ISSUE THREAD

**Issue by jbreitbart** [mank319/elementaryPlus#43]
A Solaar icon would be great, but I don't know if there exists one.

Link to solaar: https://pwr.github.io/Solaar/

**Comment by RafaelCz** [comment]
Solaar indicator + app icons:
![bildschirmfoto vom 2015-04-26 14 39 02](https://cloud.githubusercontent.com/assets/7204193/7338141/cb6bc642-ec42-11e4-8d01-0181f33a4c59.png)

**Comment by quassy** [comment]
Can't test them in elementary, but they sure look great here on GitHub ([repo](https://github.com/RafaelCz/elementaryPlus)). Could you create a pull request?

**Comment by RafaelCz** [comment]
@quassy They got already merged, together with my Gnome Encfs Manager icons.

**Comment by jbreitbart** [comment]
Thanks for the icon! It looks great! The icon however changes into a battery a few seconds after the application was started and the battery does not work well with the elementary style.

**Comment by RafaelCz** [comment]
IMHO this issue should be closed again.
Solaar is searching for [a matching iconset](https://github.com/pwr/Solaar/blob/ec0197df3d67234f7a62eb3114e44e826309f0dd/lib/solaar/ui/icons.py#L93-L98) and recognizes our icon-theme correctly as elementary. Unlike Luna, Freya unfortunately only provides the needed battery-icons in a wrong size (the big blue battery is 32px, 24px pendants are missing) and Solaar uses them instead. 
I decided against adding the missing 24px sized battery-icons, because they aren't application-specific and adding them could mess with other applications. i don't know, if the 24px battery-icons are dropped on purpose, or if this is a bug...
On the other hand, Freya provides nice and matching  keyboard- and mouse-specific battery-icons, it would be nice, if Solaar could use them instead... Or even better disable it's battery-indicator, since Freya has it's own one.

**Comment by jbreitbart** [comment]
@RafaelCz So what do you think is the best way? Open up a issue with Solaar and ask them for support of elementaryOS?

**Comment by RafaelCz** [comment]
sorry for the late answer...
the best way would be to ask the maintainer of Solaar to include a off-switch for the battery-indicator, or at least to support device specific battery status icons (gpm-keyboard-*.svg and gpm-mouse-*.svg) in elementary OS.

**Comment by quassy** [comment]
Closing, as this seems to be an issue primarily with Solaar and elementary (maybe someone should file a bug there as well): 

> Unlike Luna, Freya unfortunately only provides the needed battery-icons in a wrong size (the big blue battery is 32px, 24px pendants are missing) and Solaar uses them instead.
