### ISSUE TITLE
PPA support

### ISSUE THREAD

**Issue by orschiro** [mank319/elementaryPlus#49]
Hi @mank319 and others, 

Is it possible to package elementaryPlus into a PPA for easier installation and automatic receival of updates?

Thanks ahead!

Robert

**Comment by cybre** [comment]
Yes, I've already created a PPA but it's not ready yet (didn't have the time to finish it).
I'll probably do it in the next few days.

**Comment by orschiro** [comment]
@cybre 

That's great news! Thanks for your work.

**Comment by quassy** [comment]
@cybre Maybe we should consult @JustSomeDood he does a very nice job with his PPA [justsomeelementary](https://launchpad.net/~justsomedood/+archive/ubuntu/justsomeelementary) but he had some problems with integration the elementary+ scripts into his PPA I believe. Would be nice if elementary+ was integrated there so people don't have to add dozens of repositories.

**Comment by cybre** [comment]
@quassy But then again, not everyone wants a PPA with elementary+ and 100 other packages they (myself included) won't install.

**Comment by orschiro** [comment]
@cybre 

Does a PPA, that contains packages that you don't use, pose any disadvantage to you? 

I see an equivalent to the default Ubuntu repos. They also contain packages that I don't use but I don't feel bothered by them.

**Comment by cybre** [comment]
@orschiro No, not really, but I would prefer having it in our own PPA. You can't really take the Ubuntu repos as an equivalent since they are not really **Personal** Package Repositories (PPA). They are maintained by the Canonical Ubuntu Desktop team and come pre-installed on all Ubuntu systems.
The real reason is, any new updates can break the package build process because:
a) it fails to patch the installer because some contents changed
b) we change the directory structure
c) some other issue
I'm more comfortable fixing these issues myself that contacting someone else to do it.

**Comment by orschiro** [comment]
> I'm more comfortable fixing these issues myself that contacting someone else to do it.

This is a completely understandible reasoning. Thanks for explaining!

**Comment by quassy** [comment]
> @quassy But then again, not everyone wants a PPA with elementary+ and 50 other packages they (myself included) won't install.

Yes I agree, some people rightfully don't want that (even though I personally would)... hopefully we will have both (dedicated PPA and transfering the knowdledge of building to also have it in justsomeelementary).

**Comment by cybre** [comment]
Fixed #106
