### ISSUE TITLE
Integration of themes into elementaryPlus

### ISSUE THREAD

**Issue by orschiro** [mank319/elementaryPlus#50]
Hi all, 

I very much like your idea of the overview menu through which you can enable/disable various icons and settings. I am wondering whether this menu can be the integral interface for third-party themes for better integration of software. @quassy provides a nice [list](http://quassy.github.io/elementary-apps/art/) of themes for programs such as Thunderbird, Chrome or Thunderbird. 

If we integrate these into elementaryPlus, the user would have to install only elementaryPlus to integrate software of his choice (elements to integrate are then icons and themes). For instance, enabling the switch for Chrome would install the Chrome eOS Theme (although I am not sure whether this is possible in a passive mode). 

Looking forward to your opinion!

Robert

**Comment by quassy** [comment]
I think it's a good idea for everything which integrates stuff better into elementary (Chrome, Firefox, Sublime theme, etc) because I think that's the basic idea of elementary+. So no custom themes / stuff that does not adhere to elementary HIG. 

But it should be in separate scripts / scripts should have an option so people still have the choice.
