### ISSUE TITLE
Icon Request: Insync

### ISSUE THREAD

**Issue by orschiro** [mank319/elementaryPlus#52]
[Insync](https://www.insynchq.com/) is the most feature-rich Google Drive client on Linux and comes with the following tray indicator:

![image](https://cloud.githubusercontent.com/assets/170947/7228812/4ddcb798-e75d-11e4-9a0a-843e13bc9cd5.png)

**Comment by orschiro** [comment]
With the recent pull requests, the Insync icon does look very integrated thanks to its white colour.

![image](https://cloud.githubusercontent.com/assets/170947/7357988/cee47e36-ed32-11e4-96ec-b715af8a37ab.png)

I think we don't have to invest any energy in creating a custom icon for Insync.

**Comment by RafaelCz** [comment]
I've created elementary styled icons for Insync, including indicator icons, app icon, folder icon and all mimetype icons. Since Insync is a Google Drive client, I decided to go with the original Google Drive logo as indicator icon.
Indicator meanings:
1. Normal/synced
2. feed
3. incoming shares
4. actions required
5. syncing
6. paused
7. offline
8. partial error
9. error
![bildschirmfoto vom 2015-05-14 10 38 33](https://cloud.githubusercontent.com/assets/7204193/7681233/bd9cce3e-fd6e-11e4-96de-239df53997f7.png)
![preview-app](https://cloud.githubusercontent.com/assets/7204193/7681235/c314d104-fd6e-11e4-8d84-8d9595d21fca.png)
![preview-places](https://cloud.githubusercontent.com/assets/7204193/7681238/c90b89fe-fd6e-11e4-9065-07ed36461c55.png)
![output](https://cloud.githubusercontent.com/assets/7204193/7681239/cc15605c-fd6e-11e4-93f2-38b47129e41c.png)

**Comment by orschiro** [comment]
@RafaelCz 

What beautiful, thanks so much. Cannot await to test it!

**Comment by JrFernando** [comment]
@RafaelCz how to use the folder icon in pantheon?
For mine continues with the default icon
