### ISSUE TITLE
Errors when trying to install on Luna

### ISSUE THREAD

**Issue by Heart1010** [mank319/elementaryPlus#55]
I cloned the repo and tried to execute ./install.sh (on luna) but get this:

```bash
➜  elementaryPlus git:(master) ./install.sh
Installed components:  []
Sni-qt IS NOT patched
Traceback (most recent call last):
  File "./scripts/elementaryplus-installer", line 217, in <module>
    win = InstallerWindow()
  File "./scripts/elementaryplus-installer", line 95, in __init__
    self.hb = Gtk.HeaderBar()
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 243, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 105, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'HeaderBar'
```
Should this run on luna or only in freya?!

**Comment by quassy** [comment]
> AttributeError: 'gi.repository.Gtk' object has no attribute 'HeaderBar'

I'm not involved in the installer scripts, but judging from this error: Yes, I believe it works on Freya only.

**Comment by Heart1010** [comment]
...some info about that on readme would be nice then. Thanks.

**Comment by quassy** [comment]
Yep, we should (got little idea how to do 2 and 3):

1. Make it clear in the `README.md` that the script is only supposed to work on Freya. (Or do we want to support Luna? Guess not...)
2. Probably make the whole installation description more detailed / provide the PPA asap.
3. Include a check in `elementaryplus-installer` (which should be named `elementaryplus-installer.py` imo) for the distro version and put out a warning that the script might fail if the version is not Freya. The script should still go ahead because some people might try elementary+ on Ubuntu or other distros with Gnome 3 where it actually works.

**Comment by bil-elmoussaoui** [comment]
I think that the installer must autodetect if the user is using luna or not. And hide/show the features that can use. With a different gtk version and stuff like that.
